---
title: "Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Trial execution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

To knit this vignette, will first need to run `devtools::install()` to fetch the latest version of our `simulation` model code.

```{r, include = FALSE}
knitr::opts_chunk[["set"]](
  collapse = TRUE,
  comment = "#>"
)
```

# Set up

Import required packages.

```{r setup}
# nolint start: undesirable_function_linter.
library(simmer)
library(simmer.plot)
library(simulation)
# nolint end
```

# Run model

```{r}
envs <- trial(param = defaults())
envs %>% get_mon_arrivals() %>% head()
```

```{r}
# Get results
cat("Number of patients generated in the first simulation:",
    envs[[1L]] %>% get_n_generated("patient"), "\n")

# Aggregate and display resource monitoring results
res_monitor <- do.call(rbind, lapply(envs, get_mon_resources))
head(res_monitor)

# Aggregate and display arrival monitoring results
arrivals_monitor <- do.call(rbind, lapply(envs, get_mon_arrivals))
head(arrivals_monitor)
```

Get process and resource parameters

```{r}
env <- envs[[1L]]

env %>% get_sources()
env %>% get_resources()

env %>% get_n_generated("patient")

env %>% get_capacity("nurse")
env %>% get_queue_size("nurse")
env %>% get_server_count("nurse")
env %>% get_queue_count("nurse")
```

Get monitoring statistics

```{r}
env %>% get_mon_arrivals() %>% head()
env %>% get_mon_attributes() %>% head()
env %>% get_mon_resources() %>% head()
```

## Trajectory

```{r}
t0 <- trajectory("appointment") %>%
  seize("nurse", 1L) %>%
  timeout(function() {
    rexp(n = 1L, rate = 1L / param[["mean_n_consult_time"]])
  }) %>%
  release("nurse", 1L)

get_palette <- scales::brewer_pal(type = "qual", palette = 1)
plot(t0, fill = get_palette)
```

## Plots from `simmer.plot`

```{r}
resources <- get_mon_resources(envs)
plot(resources, metric="usage")
plot(resources, metric="utilization")
plot(resources, metric = "usage", c("nurse"), items = "server")
```

```{r}
arrivals <- get_mon_arrivals(envs)
plot(arrivals, metric = "flow_time")
plot(arrivals, metric = "activity_time")
plot(arrivals, metric = "waiting_time")
```

## Tables

Useful to look at `simmer.plot` documentation

MIT licence

Can use to help
